name: web

on:
  push:
    branches:
      - "**"
    paths:
      - web/**
      - .github/workflows/web.yml
    tags:
      - v*
  pull_request:
    branches:
      - "**"
    paths:
      - web/**
      - .github/workflows/web.yml
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

defaults:
  run:
    working-directory: web

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2.3.4

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Check for dependency updates
        run: npx david

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build static bundle
        run: npm run build

      - name: Upload static bundle
        uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: web/build

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    steps:
      - name: Download static bundle
        uses: actions/download-artifact@v2
        with:
          name: bundle
          path: public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
